#pragma kernel Black
#pragma kernel Error

uniform float4 size; 

RWStructuredBuffer<float4> output;

//----------------------------------------------------------------------------------------------------------------------
void SetPixel(uint2 pos, float4 color)
{
    output[pos.x + pos.y * size.x] = color;
}

//----------------------------------------------------------------------------------------------------------------------
[numthreads(8,8,1)]
void Black(uint3 id : SV_DispatchThreadID)
{
    float4 result = float4(0, 0, 0, 1);
	SetPixel(id.xy, result);
}

//----------------------------------------------------------------------------------------------------------------------
[numthreads(8,8,1)]
void Error(uint3 id : SV_DispatchThreadID)
{
    int distance1 = id.x - id.y;
    int distance2 = (size.x - id.x) - id.y;
    
    float lineWidth = size.x / 15.0;
    
    float4 result;
    if (abs(distance1) < lineWidth) 
    {
        result = float4(1, 1, 1, 1);
    }
    else if (abs(distance2) < lineWidth) 
    {
        result = float4(1, 1, 1, 1);
    }
    else
    { 
        result = float4(1, 0, 0, 1);
    }
    
	SetPixel(id.xy, result);
}
